# Generated by Django 4.0.3 on 2022-03-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploaded_plugins/')),
                ('active', models.BooleanField(default=True)),
                ('filename', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
