# Generated by Django 4.0.3 on 2022-03-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='entry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='version',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
